name: Run Custom Script on Self-Hosted Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: [self-hosted, testrunner]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Update path if run.sh is inside a subfolder
      - name: Make script executable
        run: chmod +x ./scripts/run.sh

      - name: Execute run script
        run: ./scripts/run.sh